[build-system]

requires = ["setuptools>=61.0"]

build-backend = "setuptools.build_meta"


[project]

name = "pleonasty"

version = "0.0.3"

authors = [
  { name="Ryan L. Boyd", email="ryan@ryanboyd.io" },
]

description = "A very simple abstraction for LLMs to get single responses to a given input."

readme = "README.MD"

requires-python = ">=3.8"

dependencies=["numpy>=1.25.2",
			  "tqdm>=4.66.1",
			  "accelerate>=0.27.2",
			  "SentencePiece>=0.1.99",
			  "protobuf>=4.25.3",
			  "bitsandbytes>=0.42.0",]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]

Homepage = "https://github.com/ryanboyd/pleonasty"

Issues = "https://github.com/ryanboyd/pleonasty/issues"